'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language =
  | 'en' // English
  | 'hi' // Hindi
  | 'ta' // Tamil
  | 'te' // Telugu
  | 'kn' // Kannada
  | 'ml' // Malayalam
  | 'mr' // Marathi
  | 'gu' // Gujarati
  | 'pa' // Punjabi
  | 'bn' // Bengali
  | 'or' // Odia
  | 'ur'; // Urdu

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  dir?: 'ltr' | 'rtl';
}

export const LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', dir: 'rtl' },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'CityPulse AI',
    tagline: 'See It. Report It. AI Solves It.',
    heroTitle: 'Empowering Citizens Through AI-Powered Civic Reporting.',
    heroSubtitle: 'Report public infrastructure issues in seconds, watch AI prioritize them, and track repairs in real-time.',
    getStarted: 'Get Started',
    exploreFeed: 'Explore Community',
    reportIssue: 'Report an Issue',
    dashboard: 'Dashboard',
    community: 'Community',
    rewards: 'Rewards',
    profile: 'Profile',
    settings: 'Settings',
    about: 'About Us',
    achievements: 'Achievements',
    login: 'Login',
    logout: 'Logout',
    guestMode: 'Continue as Guest',
    welcomeBack: 'Welcome Back',
    totalReports: 'Total Reports',
    resolved: 'Resolved',
    pending: 'Pending',
    trustScore: 'Trust Score',
    rewardPoints: 'Reward Points',
    recentActivity: 'Recent Activity',
    nearbyIssues: 'Nearby Issues',
    activeComplaints: 'Active Complaints',
    issueCategory: 'Category',
    severity: 'Severity',
    priority: 'Priority',
    location: 'Location',
    description: 'Description',
    title: 'Title',
    submit: 'Submit Report',
    submitting: 'Submitting...',
    successTitle: 'Report Submitted Successfully!',
    successSubtitle: 'AI is processing your complaint. You have earned +15 reward points.',
    aiAnalysis: 'Gemini AI Analysis',
    duplicateWarning: 'Potential Duplicate Detected',
    joinExisting: 'Join Existing Complaint',
    upvote: 'Upvote',
    support: 'Support',
    comments: 'Comments',
    status: 'Status',
    language: 'Language',
    theme: 'Theme',

    // Dashboard Page
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    quickLook: 'Here is a quick look at civic status metrics and active complaints.',
    totalReportsSub: 'Across the city',
    resolvedSub: 'Actioned repairs',
    pendingSub: 'Awaiting dispatch',
    rewardsSub: 'Available balance',
    trustSub: 'Civic reputation',
    nearbyMap: 'Nearby Complaints Map',
    nearbyMapSub: 'Click markers to view details and help endorse issues.',
    fullscreenFeed: 'Fullscreen feed',
    topContributors: 'Top Civic Contributors',
    quickTips: 'Quick Civic Tips',
    tip1: 'High-quality reports with tags increase AI trust scoring.',
    tip2: 'Upvoting verified local issues triggers municipal notifications.',
    tip3: 'Every 100 points unlock utility vouchers or transit passes.',
    weeklyActivity: 'Weekly Activity',
    weeklyActivitySub: 'Volume of issues reported across the city',
    issueCategories: 'Issue Categories',
    categoriesSub: 'Distribution of submitted complaints',
    communityFeed: 'Community Activity Feed',
    communityFeedSub: 'Live dispatch of civic reports submitted by citizens.',

    // Community Page
    exploreFeedSub: 'Explore and support verified civic complaints around your neighborhood.',
    searchPlaceholder: 'Search complaints by title, details or location...',
    allCategories: 'All Categories',
    sortByRecent: 'Most Recent',
    sortByTrending: 'Trending / Popular',
    commentsTitle: 'Comments & Community Notes',
    addCommentPlaceholder: 'Add a helpful update or verify this issue...',
    postComment: 'Comment',
    noReportsFound: 'No civic complaints found matching filters.',
    underReview: 'Under Review',
    assigned: 'Assigned',
    inProgress: 'In Progress',
    submitted: 'Submitted',

    // Rewards Page
    rewardsSubtitle: 'Earn points for verified civic reports, back neighbor reports, build reputation, and unlock premium city perks.',
    availableBalance: 'Available Balance',
    levelProgress: 'Civic Level Progress',
    levelProgressSub: 'Reach 500 points to unlock "Urban Guardian" rank',
    noviceReporter: 'Novice Reporter',
    urbanGuardian: 'Urban Guardian',
    reputationTitle: 'Reputation Trust Score',
    reputationSubtitle: 'Directly governs your report validation queues.',
    highTrustText: '✅ High Trust: Your AI audits bypass manual moderation queues.',
    lowTrustText: '⚠️ Standard Trust: Reports require peer upvotes before verification.',
    badgesTitle: 'Earned Civic Badges',
    badgesSubtitle: 'Unlock badges by reporting issues and gathering upvotes.',
    unlocked: 'UNLOCKED',
    pointsReq: 'Points Required',

    // Profile Page
    profileSub: 'Bengaluru, Karnataka',
    joinedDateText: 'Joined',
    mySubmissions: 'My Submissions',
    resolvedTickets: 'Resolved Tickets',
    pendingReview: 'Pending Review',
    submissionFeed: 'My Submitted Civic Complaints',
    submissionFeedSub: 'Track progress, updates, and votes on issues you reported.',
    noSubmissions: 'You have not submitted any reports yet.',

    // Settings Page
    settingsSubtitle: 'Configure your notification logs, select language preferences, and manage account credentials.',
    themeTitle: 'Theme & Interface',
    themeSubtitle: 'Toggle between dark mode and light mode templates.',
    darkModeEnabled: 'Dark Mode Enabled',
    langTitle: 'Language Selection',
    langSubtitle: 'Translate dashboard headers, buttons, and prompts instantly.',
    selectLanguageLabel: 'Select Language',
    notificationTitle: 'Notifications Preferences',
    notificationSubtitle: 'Control how and when you receive civic updates.',
    statusUpdates: 'Complaint Status Updates',
    statusUpdatesSub: 'Get notified when your reports shift status (e.g. Assigned, Resolved).',
    endorsements: 'Community Endorsements',
    endorsementsSub: 'Get notified when neighbors upvote or join your active complaints.',
    safetyAlerts: 'Critical Safety Alerts',
    safetyAlertsSub: 'Immediate SMS dispatch alert if a high-severity hazard is reported nearby.',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    deleteAccountSub: 'Permanently delete your profile and contribution history.'
  },
  hi: {
    appName: 'सिटीपल्स AI',
    tagline: 'देखें। रिपोर्ट करें। AI हल करेगा।',
    heroTitle: 'AI-संचालित नागरिक रिपोर्टिंग के माध्यम से नागरिकों को सशक्त बनाना।',
    heroSubtitle: 'सार्वजनिक बुनियादी ढांचे की समस्याओं को सेकंडों में रिपोर्ट करें, देखें कि AI उन्हें कैसे प्राथमिकता देता है, और वास्तविक समय में सुधार को ट्रैक करें।',
    getStarted: 'शुरू करें',
    exploreFeed: 'समुदाय का अन्वेषण करें',
    reportIssue: 'समस्या की रिपोर्ट करें',
    dashboard: 'डैशबोर्ड',
    community: 'समुदाय',
    rewards: 'पुरस्कार',
    profile: 'प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    about: 'हमारे बारे में',
    achievements: 'उपलब्धियां',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    guestMode: 'अतिथि के रूप में जारी रखें',
    welcomeBack: 'आपका स्वागत है',
    totalReports: 'कुल रिपोर्ट',
    resolved: 'हल की गई',
    pending: 'लंबित',
    trustScore: 'विश्वास स्कोर',
    rewardPoints: 'पुरस्कार अंक',
    recentActivity: 'हाल की गतिविधि',
    nearbyIssues: 'आस-पास की समस्याएं',
    activeComplaints: 'सक्रिय शिकायतें',
    issueCategory: 'श्रेणी',
    severity: 'तीव्रता',
    priority: 'प्राथमिकता',
    location: 'स्थान',
    description: 'विवरण',
    title: 'शीर्षक',
    submit: 'रिपोर्ट सबमिट करें',
    submitting: 'सबमिट किया जा रहा है...',
    successTitle: 'रिपोर्ट सफलतापूर्वक सबमिट की गई!',
    successSubtitle: 'AI आपकी शिकायत पर कार्रवाई कर रहा है। आपने +15 पुरस्कार अंक अर्जित किए हैं।',
    aiAnalysis: 'जेमिनी AI विश्लेषण',
    duplicateWarning: 'संभावित डुप्लिकेट का पता चला',
    joinExisting: 'मौजूदा शिकायत में शामिल हों',
    upvote: 'अपवोट',
    support: 'समर्थन',
    comments: 'टिप्पणियाँ',
    status: 'स्थिति',
    language: 'भाषा',
    theme: 'थीम',

    // Dashboard Page
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    quickLook: 'नागरिक स्थिति मेट्रिक्स और सक्रिय शिकायतों पर एक त्वरित नज़र।',
    totalReportsSub: 'पूरे शहर में',
    resolvedSub: 'कार्रवाई की गई मरम्मत',
    pendingSub: 'दस्ते की प्रतीक्षा',
    rewardsSub: 'उपलब्ध शेष राशि',
    trustSub: 'नागरिक प्रतिष्ठा',
    nearbyMap: 'आस-पास की शिकायतों का मानचित्र',
    nearbyMapSub: 'विवरण देखने और मुद्दों का समर्थन करने के लिए मार्करों पर क्लिक करें।',
    fullscreenFeed: 'पूर्ण स्क्रीन फीड',
    topContributors: 'शीर्ष नागरिक योगदानकर्ता',
    quickTips: 'त्वरित नागरिक सुझाव',
    tip1: 'टैग के साथ उच्च गुणवत्ता वाली रिपोर्ट AI विश्वास स्कोर बढ़ाती हैं।',
    tip2: 'सत्यापित स्थानीय मुद्दों को अपवोट करने से नागरिक सूचनाएं सक्रिय होती हैं।',
    tip3: 'प्रत्येक 100 अंक उपयोगिता वाउचर या पारगमन पास अनलॉक करते हैं।',
    weeklyActivity: 'साप्ताहिक गतिविधि',
    weeklyActivitySub: 'पूरे शहर में रिपोर्ट किए गए मुद्दों की संख्या',
    issueCategories: 'समस्या श्रेणियां',
    categoriesSub: 'सबमिट की गई शिकायतों का वितरण',
    communityFeed: 'सामुदायिक गतिविधि फीड',
    communityFeedSub: 'नागरिकों द्वारा सबमिट की गई नागरिक रिपोर्टों का लाइव प्रेषण।',

    // Community Page
    exploreFeedSub: 'अपने आस-पास की सत्यापित नागरिक शिकायतों का अन्वेषण और समर्थन करें।',
    searchPlaceholder: 'शीर्षक, विवरण या स्थान के अनुसार शिकायतें खोजें...',
    allCategories: 'सभी श्रेणियां',
    sortByRecent: 'सबसे हाल का',
    sortByTrending: 'रुझान / लोकप्रिय',
    commentsTitle: 'टिप्पणियाँ और सामुदायिक नोट्स',
    addCommentPlaceholder: 'एक उपयोगी अपडेट जोड़ें या इस समस्या को सत्यापित करें...',
    postComment: 'टिप्पणी',
    noReportsFound: 'फ़िल्टर से मेल खाने वाली कोई नागरिक शिकायत नहीं मिली।',
    underReview: 'समीक्षा के अधीन',
    assigned: 'आवंटित',
    inProgress: 'प्रगति पर',
    submitted: 'सबमिट किया गया',

    // Rewards Page
    rewardsSubtitle: 'सत्यापित नागरिक रिपोर्टों के लिए अंक अर्जित करें, पड़ोसियों की रिपोर्ट का समर्थन करें, प्रतिष्ठा बनाएं, और शहर के लाभों को अनलॉक करें।',
    availableBalance: 'उपलब्ध शेष राशि',
    levelProgress: 'नागरिक स्तर की प्रगति',
    levelProgressSub: '"शहरी संरक्षक" रैंक अनलॉक करने के लिए 500 अंकों तक पहुँचें',
    noviceReporter: 'नौसिखिया रिपोर्टर',
    urbanGuardian: 'शहरी संरक्षक',
    reputationTitle: 'प्रतिष्ठा विश्वास स्कोर',
    reputationSubtitle: 'यह सीधे आपकी रिपोर्ट सत्यापन कतारों को नियंत्रित करता है।',
    highTrustText: '✅ उच्च विश्वास: आपके AI ऑडिट मैन्युअल समीक्षा कतारों को बायपास करते हैं।',
    lowTrustText: '⚠️ मानक विश्वास: रिपोर्टों को सत्यापन से पहले साथियों के अपवोट की आवश्यकता होती है।',
    badgesTitle: 'अर्जित नागरिक बैज',
    badgesSubtitle: 'मुद्दों की रिपोर्ट करके और अपवोट प्राप्त करके बैज अनलॉक करें।',
    unlocked: 'अनलॉक किया गया',
    pointsReq: 'अंक आवश्यक',

    // Profile Page
    profileSub: 'बेंगलुरु, कर्नाटक',
    joinedDateText: 'शामिल हुए',
    mySubmissions: 'मेरी प्रस्तुतियां',
    resolvedTickets: 'हल किए गए टिकट',
    pendingReview: 'समीक्षा लंबित',
    submissionFeed: 'मेरी सबमिट की गई नागरिक शिकायतें',
    submissionFeedSub: 'आपके द्वारा रिपोर्ट किए गए मुद्दों पर प्रगति, अपडेट और वोटों को ट्रैक करें।',
    noSubmissions: 'आपने अभी तक कोई रिपोर्ट सबमिट नहीं की है।',

    // Settings Page
    settingsSubtitle: 'अपनी अधिसूचना लॉग कॉन्फ़िगर करें, भाषा प्राथमिकताएं चुनें और खाता क्रेडेंशियल प्रबंधित करें।',
    themeTitle: 'थीम और इंटरफ़ेस',
    themeSubtitle: 'डार्क मोड और लाइट मोड टेम्प्लेट के बीच टॉगल करें।',
    darkModeEnabled: 'डार्क मोड सक्षम',
    langTitle: 'भाषा चयन',
    langSubtitle: 'डैशबोर्ड हेडर, बटन और संकेतों का तुरंत अनुवाद करें।',
    selectLanguageLabel: 'भाषा चुनें',
    notificationTitle: 'सूचनाएं प्राथमिकताएं',
    notificationSubtitle: 'नियंत्रित करें कि आप नागरिक अपडेट कैसे और कब प्राप्त करते हैं।',
    statusUpdates: 'Complaint Status Updates',
    statusUpdatesSub: 'आपकी रिपोर्ट की स्थिति बदलने पर सूचित किया जाए (जैसे आवंटित, हल)।',
    endorsements: 'सामुदायिक समर्थन',
    endorsementsSub: 'जब पड़ोसी आपकी सक्रिय शिकायतों को अपवोट करते हैं या उनमें शामिल होते हैं तो सूचित किया जाए।',
    safetyAlerts: 'महत्वपूर्ण सुरक्षा चेतावनी',
    safetyAlertsSub: 'यदि पास में कोई उच्च-तीव्रता का खतरा रिपोर्ट किया जाता है तो तत्काल एसएमएस चेतावनी।',
    dangerZone: 'खतरनाक क्षेत्र',
    deleteAccount: 'खाता हटाएं',
    deleteAccountSub: 'अपनी प्रोफ़ाइल और योगदान इतिहास को स्थायी रूप से हटाएं।'
  },
  ta: {
    appName: 'சிட்டிபல்ஸ் AI',
    tagline: 'பாருங்கள். புகாரளிக்கவும். AI தீர்க்கும்.',
    heroTitle: 'AI-ஆல் இயங்கும் குடிமக்கள் புகாரளிப்பு மூலம் மக்களுக்கு அதிகாரம் அளித்தல்.',
    heroSubtitle: 'பொது உள்கட்டமைப்பு பிரச்சினைகளை நொடிகளில் புகாரளிக்கவும், AI அவற்றை எவ்வாறு முன்னுரிமைப்படுத்துகிறது என்பதைப் பார்க்கவும், மேலும் நேரடி கண்காணிப்பில் பழுதுபார்ப்புகளைப் பின்தொடரவும்.',
    getStarted: 'தொடங்குங்கள்',
    exploreFeed: 'சமூகத்தை ஆராயுங்கள்',
    reportIssue: 'பிரச்சினையைப் புகாரளி',
    dashboard: 'முகப்பு பலகை',
    community: 'சமூகம்',
    rewards: 'பரிசுகள்',
    profile: 'சுயவிவரம்',
    settings: 'அமைப்புகள்',
    login: 'உள்நுழைவு',
    logout: 'வெளியேறு',
    guestMode: 'விருந்தினராக தொடரவும்',
    welcomeBack: 'நல்வரவு',
    totalReports: 'மொத்த புகார்கள்',
    resolved: 'தீர்வு காணப்பட்டவை',
    pending: 'நிலுவையில் உள்ளவை',
    trustScore: 'நம்பிக்கை மதிப்பீடு',
    rewardPoints: 'பரிசு புள்ளிகள்',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    nearbyIssues: 'அருகிலுள்ள பிரச்சினைகள்',
    activeComplaints: 'செயலில் உள்ள புகார்கள்',
    issueCategory: 'வகை',
    severity: 'தீவிரம்',
    priority: 'முன்னுரிமை',
    location: 'இடம்',
    description: 'விளக்கம்',
    title: 'தலைப்பு',
    submit: 'புகாரைச் சமர்ப்பி',
    submitting: 'சமர்ப்பிக்கப்படுகிறது...',
    successTitle: 'புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
    successSubtitle: 'AI உங்கள் புகாரைச் செயலாக்குகிறது. நீங்கள் +15 பரிசுப் புள்ளிகளைப் பெற்றுள்ளீர்கள்.',
    aiAnalysis: 'ஜெமினி AI பகுப்பாய்வு',
    duplicateWarning: 'இதே போன்ற புகார் கண்டறியப்பட்டுள்ளது',
    joinExisting: 'தற்போதைய புகாரில் இணையுங்கள்',
    upvote: 'வாக்களி',
    support: 'ஆதரவு',
    comments: 'கருத்துகள்',
    status: 'நிலை',
    language: 'மொழி',
    theme: 'கருப்பொருள்',
  },
  te: {
    appName: 'సిటీపల్స్ AI',
    tagline: 'చూడండి. నివేదించండి. AI పరిష్కరిస్తుంది.',
    heroTitle: 'AI-ఆధారిత సివిక్ రిపోర్టింగ్ ద్వారా పౌరుల సాధికారత.',
    heroSubtitle: 'పబ్లిక్ ఇన్ఫ్రాస్ట్రక్చర్ సమస్యలను క్షణాల్లో నివేదించండి, AI వాటి ప్రాధాన్యతను గుర్తించడాన్ని చూడండి మరియు నిజ-సమయంలో పనులను ట్రాక్ చేయండి.',
    getStarted: 'ప్రారంభించండి',
    exploreFeed: 'కమ్యూనిటీని అన్వేషించండి',
    reportIssue: 'సమస్యను నివేదించండి',
    dashboard: 'డాష్‌బోర్డ్',
    community: 'కమ్యూనిటీ',
    rewards: 'బహుమతులు',
    profile: 'ప్రొఫైల్',
    settings: 'సెట్టింగ్స్',
    login: 'లాగిన్',
    logout: 'లాగౌట్',
    guestMode: 'అతిథిగా కొనసాగండి',
    welcomeBack: 'స్వాగతం',
    totalReports: 'మొత్తం నివేదికలు',
    resolved: 'పరిష్కరించబడినవి',
    pending: 'పెండింగ్',
    trustScore: 'నమ్మక స్కోరు',
    rewardPoints: 'రివార్డ్ పాయింట్లు',
    recentActivity: 'ఇటీవలి యాక్టివిటీ',
    nearbyIssues: 'దగ్గరలోని సమస్యలు',
    activeComplaints: 'క్రియాశీల ఫిర్యాదులు',
    issueCategory: 'వర్గం',
    severity: 'తీవ్రత',
    priority: 'ప్రాధాన్యత',
    location: 'స్థలం',
    description: 'వివరణ',
    title: 'శీర్షిక',
    submit: 'ఫిర్యాదు సమర్పించండి',
    submitting: 'సమర్పిస్తున్నాము...',
    successTitle: 'నివేదిక విజయవంతంగా సమర్పించబడింది!',
    successSubtitle: 'AI మీ ఫిర్యాదును పరిశీలిస్తోంది. మీరు +15 రివార్డ్ పాయింట్లను గెలుచుకున్నారు.',
    aiAnalysis: 'జెమిని AI విశ్లేషణ',
    duplicateWarning: 'ఇలాంటి ఫిర్యాదు కనుగొనబడింది',
    joinExisting: 'ఉన్న ఫిర్యాదులో చేరండి',
    upvote: 'అప్‌వోట్',
    support: 'మద్దతు',
    comments: 'వ్యాఖ్యలు',
    status: 'స్థితి',
    language: 'భాష',
    theme: 'థీమ్',
  },
  kn: {
    appName: 'ಸಿಟಿಪಲ್ಸ್ AI',
    tagline: 'ನೋಡಿ. ವರದಿ ಮಾಡಿ. AI ಪರಿಹರಿಸುತ್ತದೆ.',
    heroTitle: 'AI-ಚಾಲಿತ ನಾಗರಿಕ ವರದಿ ಮಾಡುವಿಕೆಯ ಮೂಲಕ ನಾಗರಿಕರ ಸಬಲೀಕರಣ.',
    heroSubtitle: 'ಸಾರ್ವಜನಿಕ ಮೂಲಸೌಕರ್ಯ ಸಮಸ್ಯೆಗಳನ್ನು ಕ್ಷಣಗಳಲ್ಲಿ ವರದಿ ಮಾಡಿ, AI ಅವುಗಳ ಆದ್ಯತೆಯನ್ನು ಗುರುತಿಸುವುದನ್ನು ನೋಡಿ ಮತ್ತು ನೈಜ ಸಮಯದಲ್ಲಿ ದುರಸ್ತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    exploreFeed: 'ಸಮುದಾಯವನ್ನು ಅನ್ವೇಷಿಸಿ',
    reportIssue: 'ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    community: 'ಸಮುದಾಯ',
    rewards: 'ಪ್ರಶಸ್ತಿಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    login: 'ಲಾಗಿನ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    guestMode: 'ಅತಿಥಿಯಾಗಿ ಮುಂದುವರಿಯಿರಿ',
    welcomeBack: 'ಸ್ವಾಗತ',
    totalReports: 'ಒಟ್ಟು ವರದಿಗಳು',
    resolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    pending: 'ಬಾಕಿ ಉಳಿದಿದೆ',
    trustScore: 'ನಂಬಿಕೆ ಸ್ಕೋರ್',
    rewardPoints: 'ರಿವಾರ್ಡ್ ಪಾಯಿಂಟ್‌ಗಳು',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    nearbyIssues: 'ಹತ್ತಿರದ ಸಮಸ್ಯೆಗಳು',
    activeComplaints: 'ಸಕ್ರಿಯ ದೂರುಗಳು',
    issueCategory: 'ವರ್ಗ',
    severity: 'ತೀವ್ರತೆ',
    priority: 'ಆದ್ಯತೆ',
    location: 'ಸ್ಥಳ',
    description: 'ವಿವರಣೆ',
    title: 'ಶೀರ್ಷಿಕೆ',
    submit: 'ವರದಿಯನ್ನು ಸಲ್ಲಿಸಿ',
    submitting: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    successTitle: 'ವರದಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!',
    successSubtitle: 'AI ನಿಮ್ಮ ದೂರನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿದೆ. ನೀವು +15 ರಿವಾರ್ಡ್ ಪಾಯಿಂಟ್‌ಗಳನ್ನು ಗಳಿಸಿದ್ದೀರಿ.',
    aiAnalysis: 'ಜೆಮಿನಿ AI ವಿಶ್ಲೇಷಣೆ',
    duplicateWarning: 'ಸಂಭಾವ್ಯ ನಕಲಿ ದೂರು ಪತ್ತೆಯಾಗಿದೆ',
    joinExisting: 'ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ದೂರಿಗೆ ಸೇರಿಕೊಳ್ಳಿ',
    upvote: 'ಅಪ್‌ವೋಟ್',
    support: 'ಬೆಂಬಲ',
    comments: 'ಕಾಮೆಂಟ್‌ಗಳು',
    status: 'ಸ್ಥಿತಿ',
    language: 'ಭಾಷೆ',
    theme: 'ಥೀಮ್',
  },
  ml: {
    appName: 'സിറ്റിപൾസ് AI',
    tagline: 'കാണുക. റിപ്പോർട്ട് ചെയ്യുക. AI പരിഹരിക്കും.',
    heroTitle: 'AI അധിഷ്ഠിത സിവിക് റിപ്പോർട്ടിംഗിലൂടെ പൗരന്മാരെ ശാക്തീകരിക്കുന്നു.',
    heroSubtitle: 'പൊതു അടിസ്ഥാന സൗകര്യ പ്രശ്നങ്ങൾ നിമിഷങ്ങൾക്കകം റിപ്പോർട്ട് ചെയ്യുക, AI അവയുടെ മുൻഗണന നിശ്ചയിക്കുന്നത് കാണുക, തത്സമയം നിരീക്ഷിക്കുക.',
    getStarted: 'ആരംഭിക്കുക',
    exploreFeed: 'കമ്മ്യൂണിറ്റി പരിശോധിക്കുക',
    reportIssue: 'പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    community: 'കമ്മ്യൂണിറ്റി',
    rewards: 'സമ്മാനങ്ങൾ',
    profile: 'പ്രൊഫൈൽ',
    settings: 'ക്രമീകരണങ്ങൾ',
    login: 'ലോഗിൻ',
    logout: 'ലോഗ്ഔട്ട്',
    guestMode: 'അതിഥിയായി തുടരുക',
    welcomeBack: 'സ്വാഗതം',
    totalReports: 'ആകെ റിപ്പോർട്ടുകൾ',
    resolved: 'പരിഹരിച്ചവ',
    pending: 'ബാക്കിയുള്ളവ',
    trustScore: 'വിശ്വാസ സ്കോർ',
    rewardPoints: 'റിവാർഡ് പോയിന്റുകൾ',
    recentActivity: 'സമീപകാല പ്രവർത്തനങ്ങൾ',
    nearbyIssues: 'സമീപത്തെ പ്രശ്നങ്ങൾ',
    activeComplaints: 'സജീവ പരാതികൾ',
    issueCategory: 'വിഭാഗം',
    severity: 'തീവ്രത',
    priority: 'മുൻഗണന',
    location: 'സ്ഥലം',
    description: 'വിവരണം',
    title: 'തലക്കെട്ട്',
    submit: 'റിപ്പോർട്ട് സമർപ്പിക്കുക',
    submitting: 'സമർപ്പിക്കുന്നു...',
    successTitle: 'റിപ്പോർട്ട് വിജയകരമായി സമർപ്പിച്ചു!',
    successSubtitle: 'AI നിങ്ങളുടെ പരാതി പരിശോധിക്കുന്നു. നിങ്ങൾ +15 റിവാർഡ് പോയിന്റുകൾ നേടിയിട്ടുണ്ട്.',
    aiAnalysis: 'ജെമിനി AI വിശകലനം',
    duplicateWarning: 'സമാനമായ പരാതി കണ്ടെത്തിയിട്ടുണ്ട്',
    joinExisting: 'നിലവിലുള്ള പരാതിയിൽ പങ്കാളിയാവുക',
    upvote: 'അപ്‌വോട്ട്',
    support: 'പിന്തുണയ്ക്കുക',
    comments: 'അഭിപ്രായങ്ങൾ',
    status: 'നില',
    language: 'ഭാഷ',
    theme: 'തീം',
  },
  mr: {
    appName: 'सिटीपल्स AI',
    tagline: 'पहा. रिपोर्ट करा. AI सोडवेल.',
    heroTitle: 'AI-आधारित नागरी रिपोर्टिंगद्वारे नागरिकांचे सबलीकरण.',
    heroSubtitle: 'सार्वजनिक पायाभूत सुविधांच्या समस्या सेकंदात रिपोर्ट करा, AI त्यांना कशी प्राथमिकता देतो ते पहा, आणि थेट ट्रॅक करा.',
    getStarted: 'सुरू करा',
    exploreFeed: 'समुदायात सामील व्हा',
    reportIssue: 'समस्या नोंदवा',
    dashboard: 'डॅशबोर्ड',
    community: 'समुदाय',
    rewards: 'बक्षिसे',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्ज',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    guestMode: 'अतिथी म्हणून सुरू ठेवा',
    welcomeBack: 'स्वागत आहे',
    totalReports: 'एकूण तक्रारी',
    resolved: 'निवारण झालेल्या',
    pending: 'लंबित',
    trustScore: 'विश्वासार्हता स्कोअर',
    rewardPoints: 'रिवॉर्ड पॉइंट्स',
    recentActivity: 'अलीकडील क्रियाकलाप',
    nearbyIssues: 'जवळपासच्या समस्या',
    activeComplaints: 'सक्रिय तक्रारी',
    issueCategory: 'वर्ग',
    severity: 'तीव्रता',
    priority: 'प्राधान्य',
    location: 'स्थान',
    description: 'वर्णन',
    title: 'शीर्षक',
    submit: 'तक्रार सबमिट करा',
    submitting: 'सबमिट होत आहे...',
    successTitle: 'तक्रार यशस्वीरित्या नोंदवली गेली!',
    successSubtitle: 'AI आपल्या तक्रारीवर काम करत आहे. आपण +15 रिवॉर्ड पॉइंट्स मिळवले आहेत.',
    aiAnalysis: 'जेमिनी AI विश्लेषण',
    duplicateWarning: 'संभाव्य डुप्लिकेट आढळले',
    joinExisting: 'विद्यमान तक्रारीमध्ये सामील व्हा',
    upvote: 'अपव्होट',
    support: 'पाठिंबा',
    comments: 'प्रतिक्रिया',
    status: 'स्थिती',
    language: 'भाषा',
    theme: 'थीम',
  },
  gu: {
    appName: 'સિટીપલ્સ AI',
    tagline: 'જુઓ. રિપોર્ટ કરો. AI હલ કરશે.',
    heroTitle: 'AI-સંચાલિત સિવિક રિપોર્ટિંગ દ્વારા નાગરિકોનું સશક્તિકરણ.',
    heroSubtitle: 'જાહેર માળખાકીય સમસ્યાઓ સેકન્ડોમાં રિપોર્ટ કરો, AI તેમને પ્રાધાન્ય આપે તે જુઓ, અને પ્રગતિ ટ્રૅક કરો.',
    getStarted: 'શરૂ કરો',
    exploreFeed: 'સમુદાયનું અન્વેષણ કરો',
    reportIssue: 'સમસ્યા રિપોર્ટ કરો',
    dashboard: 'ડેશબોર્ડ',
    community: 'સમુદાય',
    rewards: 'ઇનામો',
    profile: 'પ્રોફાઇલ',
    settings: 'સેટિંગ્સ',
    login: 'લોગિન',
    logout: 'લોગઆઉટ',
    guestMode: 'અતિથિ તરીકે ચાલુ રાખો',
    welcomeBack: 'સ્વાગત છે',
    totalReports: 'કુલ રિપોર્ટ',
    resolved: 'ઉકેલાયેલ',
    pending: 'બાકી',
    trustScore: 'વિશ્વાસ સ્કોર',
    rewardPoints: 'રિવૉર્ડ પૉઇન્ટ્સ',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    nearbyIssues: 'નજીકની સમસ્યાઓ',
    activeComplaints: 'સક્રિય ફરિયાદો',
    issueCategory: 'કેટેગરી',
    severity: 'તીવ્રતા',
    priority: 'પ્રાધાન્યતા',
    location: 'સ્થળ',
    description: 'વર્ણન',
    title: 'શીર્ષક',
    submit: 'ફરિયાદ સબમિટ કરો',
    submitting: 'સબમिट થઈ રહ્યું છે...',
    successTitle: 'ફરિયાદ સફળતાપૂર્વક સબમિટ થઈ ગઈ છે!',
    successSubtitle: 'AI તમારી ફરિયાદ પર પ્રક્રિયા કરી રહ્યું છે. તમે +15 રિવૉર્ડ પૉઇન્ટ મેળવ્યા છે.',
    aiAnalysis: 'જેમિની AI વિશ્લેષણ',
    duplicateWarning: 'સંભવિત નકલ મળી આવી',
    joinExisting: 'ચાલુ ફરિયાદમાં જોડાઓ',
    upvote: 'અપવોટ',
    support: 'ટેકો',
    comments: 'ટિપ્પણીઓ',
    status: 'સ્થિતિ',
    language: 'ભાષા',
    theme: 'થીમ',
  },
  pa: {
    appName: 'ਸਿਟੀਪਲਸ AI',
    tagline: 'ਵੇਖੋ. ਰਿਪੋਰਟ ਕਰੋ. AI ਹੱਲ ਕਰੇਗਾ।',
    heroTitle: 'AI-ਸੰਚਾਲਿਤ ਨਾਗਰਿਕ ਰਿਪੋਰਟਿੰਗ ਰਾਹੀਂ ਨਾਗਰਿਕਾਂ ਨੂੰ ਮਜ਼ਬੂਤ ਕਰਨਾ।',
    heroSubtitle: 'ਜਨਤਕ ਬੁਨਿਆਦੀ ਢਾਂਚੇ ਦੀਆਂ ਸਮੱਸਿਆਵਾਂ ਸਕਿੰਟਾਂ ਵਿੱਚ ਰਿਪੋਰਟ ਕਰੋ, ਵੇਖੋ AI ਉਨ੍ਹਾਂ ਨੂੰ ਕਿਵੇਂ ਪਹਿਲ ਦਿੰਦਾ ਹੈ, ਅਤੇ ਲਾਈਵ ਟ੍ਰੈਕ ਕਰੋ।',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    exploreFeed: 'ਸਮੁਦਾਏ ਦੀ ਪੜਚੋਲ ਕਰੋ',
    reportIssue: 'ਸਮੱਸਿਆ ਦੀ ਰਿਪੋਰਟ ਕਰੋ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    community: 'ਸਮੁਦਾਏ',
    rewards: 'ਇਨਾਮ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    login: 'ਲਾਗਇਨ',
    logout: 'ਲਾਗਆਊਟ',
    guestMode: 'ਮਹਿਮਾਨ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ',
    welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    totalReports: 'ਕੁੱਲ ਰਿਪੋਰਟਾਂ',
    resolved: 'ਹੱਲ ਹੋਈਆਂ',
    pending: 'ਲੰਬਿਤ',
    trustScore: 'ਭਰੋਸਾ ਸਕੋਰ',
    rewardPoints: 'ਇਨਾਮ ਅੰਕ',
    recentActivity: 'ਤਾਜ਼ਾ ਗਤੀਵਿਧੀ',
    nearbyIssues: 'ਨੇੜਲੀਆਂ ਸਮੱਸਿਆਵਾਂ',
    activeComplaints: 'ਸਰਗਰਮ ਸ਼ਿਕਾਇਤਾਂ',
    issueCategory: 'ਸ਼੍ਰੇਣੀ',
    severity: 'ਤੀਬਰਤਾ',
    priority: 'ਤਰਜੀਹ',
    location: 'ਸਥਾਨ',
    description: 'ਵੇਰਵਾ',
    title: 'ਸਿਰਲੇਖ',
    submit: 'ਰਿਪੋਰਟ ਸਬਮਿਟ ਕਰੋ',
    submitting: 'ਸਬਮਿਟ ਹੋ ਰਿਹਾ ਹੈ...',
    successTitle: 'ਰਿਪੋਰਟ ਸਫਲਤਾਪੂਰਵਕ ਸਬਮਿਟ ਹੋ ਗਈ!',
    successSubtitle: 'AI ਤੁਹਾਡੀ ਸ਼ਿਕਾਇਤ \'ਤੇ ਕਾਰਵਾਈ ਕਰ ਰਿਹਾ ਹੈ। ਤੁਸੀਂ +15 ਇਨਾਮ ਅੰਕ ਜਿੱਤੇ ਹਨ।',
    aiAnalysis: 'ਜੈਮਿਨੀ AI ਵਿਸ਼ਲੇਸ਼ਣ',
    duplicateWarning: 'ਸੰਭਾਵੀ ਦੋਹਰੀ ਰਿਪੋਰਟ ਮਿਲੀ ਹੈ',
    joinExisting: 'ਮੌਜੂਦਾ ਸ਼ਿਕਾਇਤ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    upvote: 'ਅੱਪਵੋਟ',
    support: 'ਸਮਰਥਨ',
    comments: 'ਟਿੱਪਣੀਆਂ',
    status: 'ਸਥਿਤੀ',
    language: 'ਭਾਸ਼ਾ',
    theme: 'ਥੀਮ',
  },
  bn: {
    appName: 'সিটিপালস AI',
    tagline: 'দেখুন। রিপোর্ট করুন। AI সমাধান করবে।',
    heroTitle: 'AI-চালিত নাগরিক রিপোর্টিংয়ের মাধ্যমে নাগরিকদের ক্ষমতায়ন।',
    heroSubtitle: 'জনসাধারণের অবকাঠামোগত সমস্যাগুলি কয়েক সেকেন্ডে রিপোর্ট করুন, AI কীভাবে সেগুলিকে অগ্রাধিকার দেয় তা দেখুন এবং মেরামত লাইভ ট্র্যাক করুন।',
    getStarted: 'শুরু করুন',
    exploreFeed: 'কমিউনিটি ঘুরে দেখুন',
    reportIssue: 'সমস্যা রিপোর্ট করুন',
    dashboard: 'ড্যাশবোর্ড',
    community: 'কমিউনিটি',
    rewards: 'পুরস্কার',
    profile: 'প্রোফাইল',
    settings: 'সেটিংস',
    login: 'লগইন',
    logout: 'লগআউট',
    guestMode: 'গেস্ট হিসেবে এগিয়ে যান',
    welcomeBack: 'স্বাগতম',
    totalReports: 'মোট রিপোর্ট',
    resolved: 'সমাধানকৃত',
    pending: 'অপেক্ষমাণ',
    trustScore: 'বিশ্বাসযোগ্যতা স্কোর',
    rewardPoints: 'রিওয়ার্ড পয়েন্ট',
    recentActivity: 'সাম্প্রতিক কার্যক্রম',
    nearbyIssues: 'কাছাকাছি সমস্যাগুলি',
    activeComplaints: 'সক্রিয় অভিযোগ',
    issueCategory: 'বিভাগ',
    severity: 'তীব্রতা',
    priority: 'অগ্রাধিকার',
    location: 'স্থান',
    description: 'বর্ণন',
    title: 'শিরোনাম',
    submit: 'রিপোর্ট জমা দিন',
    submitting: 'জমা হচ্ছে...',
    successTitle: 'রিপোর্ট সফলভাবে জমা হয়েছে!',
    successSubtitle: 'AI আপনার অভিযোগটি প্রক্রিয়া করছে। আপনি +১৫ রিওয়ার্ড পয়েন্ট পেয়েছেন।',
    aiAnalysis: 'জেমিনি AI বিশ্লেষণ',
    duplicateWarning: 'সম্ভাব্য অনুলিপি সনাক্ত করা হয়েছে',
    joinExisting: 'চলমান অভিযোগে যোগ দিন',
    upvote: 'আপভোট',
    support: 'সমর্থন',
    comments: 'মন্তব্যসমূহ',
    status: 'অবস্থা',
    language: 'ভাষা',
    theme: 'থিম',
  },
  or: {
    appName: 'ସିଟିପଲ୍ସ AI',
    tagline: 'ଦେଖନ୍ତୁ। ରିପୋର୍ଟ କରନ୍ତୁ। AI ସମାଧାନ କରିବ।',
    heroTitle: 'AI-ଦ୍ଵାରା ଚାଳିତ ନାଗରିକ ରିପୋର୍ଟ ସାହାଯ୍ୟରେ ଲୋକଙ୍କ ଶକ୍ତିକରଣ।',
    heroSubtitle: 'ଜନସାଧାରଣଙ୍କ ସମସ୍ୟା ଗୁଡିକୁ କିଛି ସେକେଣ୍ଡରେ ଜଣାନ୍ତୁ, AI କିପରି ସେଗୁଡିକୁ ପ୍ରାଥମିକତା ଦେଉଛି ଦେଖନ୍ତୁ ଓ ପ୍ରଗତି ଯାଞ୍ଚ କରନ୍ତୁ।',
    getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ',
    exploreFeed: 'କମ୍ୟୁନିଟି ଅନୁସନ୍ଧାନ କରନ୍ତୁ',
    reportIssue: 'ସମସ୍ୟା ଜଣାନ୍ତୁ',
    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    community: 'କମ୍ୟୁନିଟି',
    rewards: 'ପୁରସ୍କାର',
    profile: 'ପ୍ରୋଫାଇଲ୍',
    settings: 'ସେଟିଂସ',
    login: 'ଲଗ୍-ଇନ୍',
    logout: 'ଲଗ୍-ଆଉଟ୍',
    guestMode: 'ଅତିଥି ଭାବରେ ପ୍ରବେଶ କରନ୍ତୁ',
    welcomeBack: 'ସ୍ଵାଗତମ୍',
    totalReports: 'ସର୍ବମୋଟ ରିପୋର୍ଟ',
    resolved: 'ସମାଧାନ ହୋଇଥିବା',
    pending: 'ବାକି ରହିଥିବା',
    trustScore: 'ବିଶ୍ଵାସ ସ୍କୋର',
    rewardPoints: 'ପଏଣ୍ଟ ସଂଖ୍ୟା',
    recentActivity: 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ',
    nearbyIssues: 'ନିକଟବର୍ତ୍ତୀ ସମସ୍ୟା',
    activeComplaints: 'ସକ୍ରିୟ ଅଭିଯୋଗ',
    issueCategory: 'ଶ୍ରେଣୀ',
    severity: 'ତୀବ୍ରତା',
    priority: 'ପ୍ରାଥମିକତା',
    location: 'ସ୍ଥାନ',
    description: 'ବିବରଣୀ',
    title: 'ଶିରୋନାମା',
    submit: 'ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ',
    submitting: 'ଦାଖଲ ହେଉଛି...',
    successTitle: 'ରିପୋର୍ଟ ସଫଳତାର ସହ ଦାଖଲ ହେଲା!',
    successSubtitle: 'AI ଆପଣଙ୍କ ଅଭିଯୋଗର ବିଶ୍ଳେଷଣ କରୁଛି। ଆପଣ +୧୫ ପଏଣ୍ଟ ଅର୍ଜନ କଲେ।',
    aiAnalysis: 'ଜେମିନି AI ବିଶ୍ଳେଷଣ',
    duplicateWarning: 'ନକଲି ରିପୋର୍ଟର ସମ୍ଭାବନା ଅଛି',
    joinExisting: 'ବର୍ତ୍ତମାନର ଅଭିଯୋਗରେ ସାମିଲ ହୁଅନ୍ତୁ',
    upvote: 'ଅପଭୋଟ୍',
    support: 'ସମର୍ଥନ',
    comments: 'ମତାମତ',
    status: 'ସ୍ଥିତି',
    language: 'ଭାଷା',
    theme: 'ଥୀମ୍',
  },
  ur: {
    appName: 'سٹی پلس AI',
    tagline: 'دیکھیں۔ رپورٹ کریں۔ AI حل کرے گا۔',
    heroTitle: 'AI سے چلنے والی شہری رپورٹنگ کے ذریعے شہریوں کو بااختیار بنانا۔',
    heroSubtitle: 'عوامی انفراسٹرکچر کے مسائل سیکنڈوں میں رپورٹ کریں، دیکھیں کہ AI ان کو کیسے ترجیح دیتا ہے، اور پیش رفت دیکھیں۔',
    getStarted: 'شروع کریں',
    exploreFeed: 'برادری میں شامل ہوں',
    reportIssue: 'مسئلہ رپورٹ کریں',
    dashboard: 'ڈیش بورڈ',
    community: 'برادری',
    rewards: 'انعامات',
    profile: 'پروفائل',
    settings: 'ترتیبات',
    login: 'لاگ ان',
    logout: 'لاگ آؤٹ',
    guestMode: 'بطور مہمان جاری رکھیں',
    welcomeBack: 'خوش آمدید',
    totalReports: 'کل رپورٹیں',
    resolved: 'حل شدہ',
    pending: 'التواء میں',
    trustScore: 'ساکھ کا سکور',
    rewardPoints: 'انعام کے پوائنٹس',
    recentActivity: 'حالیہ سرگرمی',
    nearbyIssues: 'قریبی مسائل',
    activeComplaints: 'سرگرم شکایات',
    issueCategory: 'زمرہ',
    severity: 'شدت',
    priority: 'ترجیح',
    location: 'مقام',
    description: 'تفصیل',
    title: 'عنوان',
    submit: 'رپورٹ جمع کروائیں',
    submitting: 'جمع ہو رہا ہے...',
    successTitle: 'رپورٹ کامیابی سے جمع ہو گئی!',
    successSubtitle: 'AI آپ کی شکایت پر کارروائی کر رہا ہے۔ آپ نے +15 پوائنٹس حاصل کیے ہیں۔',
    aiAnalysis: 'جیمنی AI تجزیہ',
    duplicateWarning: 'ممکنہ نقل کا پتہ چلا ہے',
    joinExisting: 'موجودہ شکایت میں شامل ہوں',
    upvote: 'اپ ووٹ',
    support: 'حمایت',
    comments: 'تبصرے',
    status: 'حالت',
    language: 'زبان',
    theme: 'تھیم',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && translations[savedLang]) {
      setLanguage(savedLang);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    if (translations[lang]) {
      setLanguage(lang);
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const currentLangInfo = LANGUAGES.find((l) => l.code === language);
  const dir = currentLangInfo?.dir || 'ltr';

  useEffect(() => {
    // Set HTML dir attribute dynamically for RTL languages like Urdu
    window.document.documentElement.dir = dir;
    window.document.documentElement.lang = language;
  }, [dir, language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
